version: "3.8"
services:
  silverstripe:
    ports:
      - 8989:80
    working_dir: /var/www
    volumes:
       - .:/var/www/html
    build: .
    

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
       - db-data:/var/lib/mysql
volumes:
     db-data: